## Math 157: Intro to Mathematical Software
## UC San Diego, winter 2018

## March 5, 2018: Julia (part 2 of 3)
## Guest lecture by Alyson Deines (Center for Communications Research)

Administrivia:

- CAPE evaluations are available! They close Monday, March 19 at 8am. Since this course is highly experimental, your feedback will be very helpful for shaping future offerings.
- No sections on Tuesday, March 6. However, during this time, you are welcome to use APM 6402 as a study room; we will also try to monitor the chat room.
- Thomas's office hours (usually Tuesday 11am-12pm) are moved to Friday 11:30am-12:50pm.
- Peter's office hours (usually Wednesday 3-5pm) are moved to Wednesday 5-7pm. 
- There will be an extra virtual office hour Thursday 6-7pm.
 
Advance notice for week 10:
- No lectures on Monday, March 12 or Wednesday, March 14. You may wish to use this time to meet your final project group.
- There will be a lecture on Friday, March 16, on the topic of "Where to go from here?" This lecture will not be counted for course attendance; that is, the last lecture for which attendance counts is Friday, March 9.
- My office hours on Thursday, March 15 are cancelled. All other sections and office hours meet as scheduled.

### Final project news

- Both parts will be collected Sunday, March 18 at 8pm.
- The groups for part 2 have been assigned. See the file `final_project_groups.md` in the shared project; then contact your group members as soon as possible. (I have created workspaces and chat rooms which may help with this; these are described in the same file.)
- For part 1, problem 4b, instead of the exhaustive search, do random sampling with $10^4$ samples. Ditto for 4c.

### Linear Algebra in Julia

https://docs.julialang.org/en/stable/manual/linear-algebra/

### Vectors and Matrices

Julia views vectors as flat arrays and matrices as two-dimentional arrays.

To get a "row" vector:

In [7]:
[1 2 3]

1×3 Array{Int64,2}:
 1  2  3

To get a "column" vector:

In [8]:
[1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [3]:
v = [2, -1, 4]
w = [1, 0, -3]
println(v)
println(w)

[2, -1, 4]
[1, 0, -3]


In [0]:
v + 3*w # Addition, scalar multiplication

In [0]:
dot(v, w)

In [0]:
cross(v, w)

In [0]:
v*transpose(w)

In [0]:
transpose(v)*w

In [0]:
# Easier transpose
v'*w

In [0]:
# Doesn't automatically dot
v*w

In [0]:
?norm

In [0]:
norm(v, 1)

In [0]:
norm(v, 2)

In [0]:
sqrt(v'v)

## Vectorized Functions

A vectorized function is a function $f(x)$ that simply applies to every element of an array $A$ to yield $f(A)$.  The syntax in Julia for this is $f.(A)$.

In [0]:
log(1.0)

In [0]:
log.(ones(4))

In [0]:
v

In [0]:
log.(complex.(v'))

In [0]:
sin.(v')

## Matrices:

In [0]:
M = [1 -1 0; -2 2 -1; 0 1 3]
det(M)

In [0]:
trace(M)

In [0]:
eigvals(M)

In [0]:
evals, evecs = eig(A)

In [0]:
rank(M)

In [0]:
nullspace(M)

In [0]:
typeof(M)

In [0]:
# Careful
M0 = [[1, -1, 0], [-2, 2, -1], [0, 1, 3]]
println(typeof(M0))
M1 = [[1 -1 0] [-2 2 -1] [0 1 3]]
println(typeof(M1))

In [0]:
M1 == M

In [0]:
M

In [0]:
M0

In [0]:
M1

In [0]:
M == [[1 -1 0]; [-2 2 -1]; [0 1 3]]

In [0]:
# And keep being careful
[v w]

In [0]:
[transpose(v); transpose(w)]

In [0]:
[v'; w']

In [0]:
I3 = eye(Int, 3) # Identity matrix

In [0]:
M + I3  #Matrix addition

In [0]:
# Note, assumes float not int:
eye(3)

In [0]:
M*M  # Matrix multiplication

You don't always need * for multiplication

In [0]:
M'M

Here is where things start looking even more like numpy and a lot less like Sage.

In [0]:
# Rows, Cols
size(M)

In [0]:
# Careful
M[1] # Doesn't extract a row

In [0]:
# Extract a row
M[1, :]'

In [0]:
# Extract a column
M[:, 2]

In [0]:
M

In [0]:
# Stacks columns as a vector
M[:]

In [0]:
# Stacks rows as a vector
M'[:]

Solve a system.  Note we can force the matrix and vector to have entries of a specific type.

In [0]:
A = Rational[3 2 -1; 2 1 -1; 1 -1 1]
b = Rational[1, -1, 2]
A\b

vs.

In [0]:
A = [3 2 -1; 2 1 -1; 1 -1 1]
b = [1, -1, 2]
A\b

In [0]:
w = [1/3, 5/3, 10/3]

In [0]:
A*w

In [0]:
inv(A)

In [0]:
A

Several ways to add rows and columns:

In [0]:
[A;[1 3 4]]

In [0]:
[A; [1, 3, 4]']

In [0]:
cat(1, A, [1 3 4])

In [0]:
[A';[1, 3, 4]']'

In [0]:
cat(2, A, [1, 3, 4])

In [0]:
[A M]

In [0]:
[A; M]

In [0]:
zeros(5, 10)

In [0]:
diag(A)

In [0]:
diag(M)

A few numpy-ish functions on matrices

In [0]:
A^3

In [0]:
sum(A)

In [0]:
mean(A)

In [0]:
max.(A, M)

In [0]:
min.(A, M)

In [0]:
norm(A)

In [0]:
norm(A[:])

In [0]:
?norm